name: "[question]"
description: Make a question related to the project
title: "[Question]: "
labels: question
body:
  - type: textarea
    attributes:
      label: Question
      description: Please describe your question in detail
      placeholder: "What would you like to ask?"
    validations:
      required: true
